# Generated by Django 2.1.7 on 2019-04-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
