# Generated by Django 2.1.7 on 2019-04-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20190420_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='tiger.jpg', upload_to='product_pics'),
        ),
    ]
