# Generated by Django 2.1.7 on 2019-04-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20190420_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='profile',
        ),
    ]
