# Generated by Django 2.1.7 on 2019-04-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20190420_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
    ]
