# Generated by Django 2.1.7 on 2019-04-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_remove_profile_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecom.Cart'),
            preserve_default=False,
        ),
    ]
