# Generated by Django 2.1.7 on 2019-04-20 23:06

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='buyern',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=None, size=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='productn',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=None, size=100),
            preserve_default=False,
        ),
    ]
