# Generated by Django 2.1.7 on 2019-04-20 23:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0014_auto_20190420_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='buyern',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='productn',
            field=django_mysql.models.ListTextField(models.IntegerField(), null=True, size=100),
        ),
    ]
