# Generated by Django 2.1.7 on 2019-04-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_auto_20190421_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='buyern',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='productn',
        ),
        migrations.AddField(
            model_name='product',
            name='buyer',
            field=models.IntegerField(default=-1),
        ),
    ]
